# Shared / global
base_dir: /data/homes/yl814/episcope_test/nutrient_stress_strict_JASPAR2024
ref_genome: hg38  # one of: hg38, mm10
db: JASPAR2024  # one of: JASPAR2024, HOCOMOCOv13

# Module 1: Predict TF binding sites
fp_root_dir: /data/homes/cy232/cutntag/humanPDAC/Nutrients_basal/TOBIAS_merged_peaks
tf_binding_mode: all  # canonical | all
all_mode_tf_chunk_size: 5  # used only when tf_binding_mode=all and tf_subset is not set

# Module 2: Connect TFs to target genes
metadata_path: /data/homes/yl814/episcope_test/nutrient_stress_strict_JASPAR2024/data/sample_metadata_strict.csv
atac_master: /data/homes/yl814/episcope_test/nutrient_stress_strict_JASPAR2024/data/atac_master.csv
rna_path: /data/homes/yl814/episcope_test/nutrient_stress_strict_JASPAR2024/data/rna_strict.csv
tf_target_link_mode: genehancer  # genehancer | window | loops
genehancer_path: /data/homes/yl814/package/episcope/inst/extdata/GeneHancer_v5.24_elite_panc.csv
link_window_bp: 30000
link_gene_id_col: HGNC
# loop_path: /path/to/loops.tsv

# Module 2: Basal network thresholds
threshold_tf_expr: 10
threshold_gene_expr: 4
threshold_fp_score: 2
threshold_link_score: 2
atac_score_threshold: 0
threshold_fp_tf_corr_p: 0.05
threshold_fp_tf_corr_r: 0.3          # positive only
threshold_fp_gene_corr_p: 0.05
threshold_fp_gene_corr_abs_r: 0.3    # positive & negative
threshold_rna_gene_corr_p: 0.05
threshold_rna_gene_corr_abs_r: 0.3   # positive
threshold_atac_gene_corr_p: 0.05
threshold_atac_gene_corr_abs_r: 0.3  # positive & negative
link_score_threshold: 0.001
fp_score_threshold: 0.001

# Module 3: Differential links
de_gene_log2_abs_min: 0.5
delta_fp_cutoff: 0.5

# Module 3: Topics / reporting
topic_k: 10
